---
name: "CI Testing Bash SCript"

"on":
  workflow_dispatch:
  pull_request:
    branches:
      - "customize"
    paths:
      - 'action.sh'
      - '.github/workflows/ci.yml'


permissions:
  contents: read


jobs:
  test:
    name: CI/CD Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Start Shellcheck
        run: shellcheck *.sh
